"use client";

import Link from "next/link";

const warningSigns = [
  "Someone asks you to disable two-factor authentication.",
  "A person asks for the verification code generated by your authenticator app.",
  "You receive an unexpected login or authentication request.",
  "Someone tells you that they need your 2FA code to help secure your account.",
  "You receive repeated authentication requests that you did not initiate.",
  "Someone pressures you to approve a login you do not recognise.",
  "You are asked to share screenshots of your authenticator app.",
  "A person claiming to be support asks you to reveal your 2FA code.",
];

const methods = [
  {
    title: "Authenticator app",
    text: "An authenticator app generates temporary verification codes that can be used as an additional authentication factor.",
  },
  {
    title: "SMS verification",
    text: "A temporary code can be sent to your registered phone number to help verify a login or sensitive action.",
  },
  {
    title: "Security keys",
    text: "A physical security key can provide strong protection against many forms of account takeover and phishing.",
  },
  {
    title: "Approval prompts",
    text: "Some services send an authentication request to a trusted device that you must approve before access is granted.",
  },
];

export default function TwoFactorPage() {
  return (
    <main className="min-h-screen bg-white text-black dark:bg-[#050505] dark:text-white px-5 py-8 pb-24">

      <div className="max-w-md mx-auto">

        <Link
          href="/settings/education"
          className="inline-flex items-center text-sm text-zinc-500 hover:text-black dark:hover:text-white transition"
        >
          ← Security Education
        </Link>

        <div className="mt-7">

          <div className="w-14 h-14 rounded-2xl bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-900 flex items-center justify-center text-2xl">
            🛡️
          </div>

          <p className="text-xs text-zinc-500 uppercase tracking-widest mt-6">
            Account & Authentication
          </p>

          <h1 className="text-3xl font-black mt-2">
            Two-Factor Authentication
          </h1>

          <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-3 leading-6">
            Learn how two-factor authentication adds another layer of
            protection when someone tries to access your account.
          </p>

        </div>


        {/* IMPORTANT */}

        <section className="mt-7 p-5 rounded-2xl border border-green-200 dark:border-green-900 bg-green-50 dark:bg-green-950/20">

          <p className="font-black text-green-700 dark:text-green-300">
            🛡️ The most important rule
          </p>

          <p className="text-sm text-green-700/80 dark:text-green-300/80 mt-2 leading-6">
            Keep two-factor authentication enabled on important accounts
            and never approve a login or share a verification code that you
            did not initiate.
          </p>

        </section>


        {/* WHAT IS 2FA */}

        <section className="mt-8">

          <h2 className="text-xl font-black">
            What is two-factor authentication?
          </h2>

          <div className="mt-4 p-5 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-[#18181B]">

            <p className="text-sm text-zinc-600 dark:text-zinc-300 leading-6">
              Two-factor authentication, often called 2FA, requires an
              additional verification step after your password. This means
              that knowing your password alone may not be enough to access
              your account.
            </p>

          </div>

        </section>


        {/* HOW IT WORKS */}

        <section className="mt-8">

          <h2 className="text-xl font-black">
            How 2FA protects you
          </h2>

          <div className="mt-4 space-y-3">

            {[
              ["1", "You enter your password", "You provide your normal login credentials."],
              ["2", "Another check is required", "The service asks for an additional verification step."],
              ["3", "You verify the login", "You use an approved method such as an authenticator code, security key or authentication prompt."],
              ["4", "Access is granted", "The account can be accessed only after the additional verification succeeds."],
            ].map(([number, title, text]) => (

              <div
                key={number}
                className="flex gap-4 p-4 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-[#18181B]"
              >

                <span className="w-9 h-9 shrink-0 rounded-full bg-black dark:bg-white text-white dark:text-black flex items-center justify-center font-black text-sm">
                  {number}
                </span>

                <div>

                  <p className="font-bold">
                    {title}
                  </p>

                  <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-1 leading-6">
                    {text}
                  </p>

                </div>

              </div>

            ))}

          </div>

        </section>


        {/* METHODS */}

        <section className="mt-8">

          <h2 className="text-xl font-black">
            Common 2FA methods
          </h2>

          <div className="mt-4 space-y-3">

            {methods.map((method) => (

              <div
                key={method.title}
                className="p-5 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-[#18181B]"
              >

                <p className="font-bold">
                  {method.title}
                </p>

                <p className="text-sm text-zinc-500 dark:text-zinc-400 mt-2 leading-6">
                  {method.text}
                </p>

              </div>

            ))}

          </div>

        </section>


        {/* WARNING SIGNS */}

        <section className="mt-8">

          <h2 className="text-xl font-black">
            🚩 Warning signs
          </h2>

          <div className="mt-4 space-y-2">

            {warningSigns.map((flag) => (

              <div
                key={flag}
                className="flex gap-3 p-4 rounded-2xl bg-zinc-100 dark:bg-[#18181B] border border-zinc-200 dark:border-zinc-800"
              >

                <span className="text-red-500">
                  •
                </span>

                <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-6">
                  {flag}
                </p>

              </div>

            ))}

          </div>

        </section>


        {/* PROTECT YOURSELF */}

        <section className="mt-8">

          <h2 className="text-xl font-black">
            🛡️ Protect your 2FA
          </h2>

          <div className="mt-4 p-5 rounded-2xl border border-green-200 dark:border-green-900 bg-green-50 dark:bg-green-950/20">

            <ul className="space-y-3 text-sm text-green-800 dark:text-green-300">

              <li>• Keep two-factor authentication enabled on important accounts.</li>

              <li>• Never share authentication codes with another person.</li>

              <li>• Never approve a login request you did not initiate.</li>

              <li>• Do not share screenshots of your authenticator codes or recovery information.</li>

              <li>• Keep your recovery methods secure and up to date.</li>

              <li>• Store recovery codes somewhere secure if the service provides them.</li>

              <li>• Be suspicious of anyone who asks you to disable 2FA.</li>

              <li>• Use official support channels if you have trouble accessing your account.</li>

            </ul>

          </div>

        </section>


        {/* UNEXPECTED REQUEST */}

        <section className="mt-8 p-5 rounded-2xl border border-yellow-200 dark:border-yellow-900 bg-yellow-50 dark:bg-yellow-950/20">

          <h2 className="font-black text-yellow-800 dark:text-yellow-300">
            🚨 You received an unexpected 2FA request
          </h2>

          <ol className="mt-3 space-y-2 text-sm text-yellow-800 dark:text-yellow-300 leading-6">

            <li>1. Do not approve the request.</li>

            <li>2. Do not share the verification code.</li>

            <li>3. Check your account for unfamiliar login activity.</li>

            <li>4. Change your password if you believe someone knows it.</li>

            <li>5. Review your account security settings.</li>

            <li>6. Contact the service through its official support channel if necessary.</li>

          </ol>

        </section>


        <div className="mt-8 text-center">

          <p className="text-xs text-zinc-500">
            Two layers of protection are stronger than one.
          </p>

        </div>

      </div>

    </main>
  );
}
